### ISSUE TITLE
doesn't build with kernel 4.14

### ISSUE THREAD

**Issue by CvH** [manio/vdr-plugin-dvbapi#122]
the plugin doesn't build anymore due the drop of `CA_SET_PID` at linux kernel >=4.14
https://github.com/torvalds/linux/commit/833ff5e7feda1a042b83e82208cef3d212ca0ef1 (at least I guess it is due that drop)

```
BUILD    vdr-plugin-dvbapi (target)
/builddir/toolchain/bin/x86_64-libreelec-linux-gnu-g++ -march=x86-64 -m64 -fomit-frame-pointer -Wall -pipe -Os -flto -ffat-lto-objects -mmmx -msse -msse2 -mfpmath=sse -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -c -DPLUGIN_NAME_I18N='"dvbapi"' -DGITVERSION='"-GIT-fcd6deb"' -DLIBDVBCSA  -o CAPMT.o CAPMT.cpp
In file included from Filter.h:24:0,
                 from SocketHandler.h:34,
                 from CAPMT.h:26,
                 from CAPMT.cpp:19:
DeCSA.h:83:40: error: 'ca_pid_t' has not been declared
   bool SetCaPid(uint8_t adapter_index, ca_pid_t *ca_pid);
                                        ^~~~~~~~
In file included from CAPMT.h:26:0,
                 from CAPMT.cpp:19:
SocketHandler.h:87:3: error: 'ca_pid_t' does not name a type; did you mean '__pid_t'?
   ca_pid_t ca_pid;
   ^~~~~~~~
   __pid_t
```

**Comment by manio** [comment]
Thanks!
Can you check with: https://pastebin.com/MUe24zXW ?

**Comment by CvH** [comment]
https://pastebin.com/ZWxUify4 compiles (I have no setup to test it), tx for quick response :)

**Comment by manio** [comment]
Thanks!

**Comment by qwerty286** [comment]
Hi Manio could you renew the links upper they are no longer active 
thanks

**Comment by CvH** [comment]
@qwerty286 its that change https://github.com/manio/vdr-plugin-dvbapi/commit/7d51cc457823156d446d06c6ae40f850958fa735

works for vdr 2.2 and 2.3 branch
